export const workoutParts = [
  "Chest",
  "Back",
  "Shoulders",
  "Legs",
  "Arm",
  "Abs",
  "Cardio",
  "Full Body",
];

export const workouts = {
  Chest: [
    "Bench Press",
    "Incline Bench Press",
    "Dumbbell Bench Press",
    "Dumbbell Incline Bench Press",
    "Cable Fly",
    "Push Ups",
    "Dips",
    "Pec Deck Machine",
  ],
  Back: [
    "Pull Up",
    "Deadlift",
    "Lat Pulldown",
    "Bent-over Rows",
    "T-bar Rows",
    "Single-arm Dumbbell Row",
    "Seated Cable Row",
  ],
  Shoulders: [
    "Shoulder Press",
    "Lateral Raise",
    "Front Raise",
    "Arnold Press",
    "Shrugs",
    "Face Pull",
    "Reverse Fly",
  ],
  Legs: [
    "Squat",
    "Lunges",
    "Leg Press",
    "Romanian Deadlift",
    "Leg Curl",
    "Leg Extension",
    "Calf Raise",
    "Step Ups",
  ],
  Arm: [
    "Bicep Curl",
    "Tricep Dips",
    "Hammer Curl",
    "Concentration Curl",
    "Skull Crushers",
    "Overhead Tricep Extension",
    "Cable Pushdown",
  ],
  Abs: [
    "Crunch",
    "Leg Raise",
    "Plank",
    "Bicycle Crunch",
    "Mountain Climbers",
    "Hanging Knee Raise",
    "Russian Twists",
  ],
  Cardio: [
    "Running",
    "Cycling",
    "Rowing",
    "Jump Rope",
    "Burpees",
    "High Knees",
  ],
  FullBody: [
    "Clean and Jerk",
    "Snatch",
    "Burpees",
    "Thrusters",
    "Kettlebell Swings",
    "Battle Ropes",
  ],
};
